---
- name: Prepare server
  become: yes
  block:
  - name: Install Python
    yum:
      name: python36
  - name: Install server
    pip:
      name: too-simple-server

- name: Configure and start
  when: server_state == 'present'
  block:
  - name: Write configuration
    template:
      src: config.yml.j2
      dest: "{{ server_config }}"
      force: yes

  - name: Start server
    command: "{{ server }} start --config {{ server_config }}"
    args:
      creates: "{{ server_pid_file }}"

- name: Stop server
  command: "{{ server }} stop"
  args:
    removes: "{{ server_pid_file }}"
  when: server_state == 'absent'