---
- name: Prepare server
  become: yes
  block:
  - name: Download too-simple-server
    get_url:
      url: "{{ download_path }}"
      dest: /tmp/

  - name: Extract too-simple-server into /usr/bin/
    unarchive:
      src: "/tmp/{{ server_archive_name }}"
      dest: /usr/bin/
      remote_src: yes

- name: Configure and start
  when: server_state == 'present'
  block:

  - name: Create config dir
    become: yes
    file:
      mode: 0777
      path: "{{ server_config_dir }}"
      state: directory

  - name: Write configuration
    template:
      src: config.yml.j2
      dest: "{{ server_config }}"
      force: yes
  - name: Start server
    command: "{{ server }} --config {{ server_config }}"
    args:
      creates: "{{ server_pid_file }}"

- name: Stop server
  command: "{{ server }} stop"
  args:
    removes: "{{ server_pid_file }}"
  when: server_state == 'absent'
