terraform_version: "0.14.3"
local_private_key: "~/.ssh/{{ key_name }}-test"
test_host_keyfile: "/tmp/test_host_rsa-test"
terraform_workspace: test-infra
terraform_network_cidr: "192.168.0.0/16"
controller_address: ""
