---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
    test_host:
      ansible_user: "linux"
      ansible_host: "80.158.33.71"                                                                        #"{{ test_host_address }}"
      ansible_ssh_private_key_file: "{{ test_host_keyfile }}"
