---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: '/usr/bin/env python3'
  children:
    scn1_ecs:  # group, runtime-populated
      hosts:
    scn1_gatewayed:
      hosts:
    scn2_ecs:  # group, runtime-populated
      hosts:
