---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: '/usr/bin/env python3'
    bastion:
      ansible_ssh_user: "linux"
      ansible_host: "ecs-{{ lookup('env', 'BASTION_PUBLIC_IP') | replace('.','-')}}.reverse.open-telekom-cloud.com"
  children:
    scn1_ecs:  # group, runtime-populated
      hosts:
        bastion:
    scn2_ecs:  # group, runtime-populated
      hosts:
        web_server:
