---
- name: Create key pair for lb monitoring
  openstack.cloud.keypair:
    name: "{{ keypair }}"
    public_key_file: "{{ key_path }}.pub"
  register: keypair

- name: Create ecs nodes and loadbalancer
  include_role:
    name: "{{ item }}"
  loop:
    - ecs_node
    - loadbalancer
  vars:
    state: present
    scenario_name: "{{ scenario }}"
    ecs_network_id: "{{ lb_network_id }}"
    ecs_image: "{{ lb_nodes_image }}"
    ecs_flavor: "{{ lb_nodes_flavor }}"
    ecs_key_pair_name: "{{ keypair.key.name }}"
    ecs_availability_zones: "{{ lb_nodes_availability_zones }}"
    ecs_count: "{{ lb_nodes_count }}"
    loadbalancer_instances: "{{ instances }}"
    loadbalancer_members_count: "{{ instances.results|length }}"
    loadbalancer_subnet_id: "{{ lb_subnet_id }}"
    loadbalancer_lb_local_ip:  "{{ lb_local_ip }}"
    loadbalancer_protocol: "{{ lb_protocol }}"
    loadbalancer_protocol_port: "{{ lb_protocol_port }}"
    loadbalancer_monitor_delay: "{{ lb_monitor_delay }}"
    loadbalancer_monitor_timeout: "{{ lb_monitor_timeout }}"
    loadbalancer_monitor_max_retries: "{{ lb_monitor_max_retries }}"
    loadbalancer_pool_lb_method: "{{ lb_pool_lb_method }}"
