---
- job:
    name: python-lint
    parent: otc-tox-pep8
    voting: false

- job:
    name: ansible-lint
    parent: otc-tox
    voting: false
    vars:
      tox_envlist: yamllint

- job:
    name: terraform-lint
    parent: simpleton
    voting: false
    vars:
      simple_source_image: "ubuntu:latest"
      simple_prerun:
        - sh ./scripts/prepare-terraform.sh
      simple_run:
        - sh ./scripts/terraform-lint.sh

- job:
    name: tox-cover-docker
    parent: tox-cover
    nodeset: ubuntu-focal
    pre-run: ./tests/postgres/pre.yaml
    voting: false

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - terraform-lint
        - python-lint
        - ansible-lint
        - tox-cover-docker
    gate:
      jobs:
        - terraform-lint
        - python-lint
        - ansible-lint
        - tox-cover-docker
