---
- job:
    name: terraform-lint
    parent: otc-tox
    vars:
      tox_envlist: tflint

- job:
    name: otc-tox-functional
    parent: tox-functional
    nodeset: debian-buster

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - tox-linters-ansible-2.9
        - tox-linters-ansible-2.10
        - tox-molecule-29
        - tox-molecule-210
    check-post:
      jobs:
        - otc-tox-functional
    gate:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - tox-linters-ansible-2.9
        - tox-linters-ansible-2.10
        - otc-tox-functional
        - tox-molecule-29
        - tox-molecule-210
