---
- job:
    name: terraform-lint
    parent: otc-tox
    vars:
      tox_envlist: tflint

- job:
    name: tox-cover-docker
    parent: tox-cover
    nodeset: debian-buster
    pre-run: ./tests/docker/pre.yaml

- job:
    name: tox-functional-wrapped
    parent: tox-functional
    nodeset: debian-buster
    pre-run: ./tests/bwrap/pre.yaml
    description: >
      Run `functional` tox environment on debian machine
      with `bubblewrap` installed

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - tox-linters-ansible-2.9
        - tox-linters-ansible-2.10
        - tox-cover-docker
        - tox-molecule-29
        - tox-molecule-210
    check-post:
      jobs:
        - tox-functional-wrapped
    gate:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - tox-linters-ansible-2.9
        - tox-linters-ansible-2.10
        - tox-functional-wrapped
        - tox-cover-docker
        - tox-molecule-29
        - tox-molecule-210
