---
- job:
    name: ansible-lint
    parent: otc-tox
    vars:
      tox_envlist: yamllint

- job:
    name: terraform-lint
    parent: otc-tox
    vars:
      tox_envlist: tflint

- job:
    name: tox-cover-docker
    parent: tox-cover
    nodeset: ubuntu-focal
    pre-run: ./tests/docker/pre.yaml

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - ansible-lint
        - tox-cover-docker
        - tox-molecule-29
        - tox-molecule-210
    gate:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - ansible-lint
        - tox-cover-docker
        - tox-molecule-29
        - tox-molecule-210
