---
- job:
    name: terraform-lint
    parent: otc-tox
    vars:
      tox_envlist: tflint

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - otc-tox-linters
        - tox-molecule-29
        - tox-molecule-210
    gate:
      jobs:
        - terraform-lint
        - otc-tox-pep8
        - otc-tox-linters
        - tox-molecule-29
        - tox-molecule-210
