---
- job:
    name: python-lint
    parent: otc-tox
    voting: false

- job:
    name: ansible-lint
    parent: otc-tox
    voting: false

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - python-lint
        - ansible-lint
    gate:
      jobs:
        - python-lint
        - ansible-lint
