---
  - name: opentelekomcloud.vpc
    # src: https://github.com/opentelekomcloud/ansible-role-otc-vpc.git
  - name: opentelekomcloud.keypair
    # src: https://github.com/opentelekomcloud/ansible-role-otc-keypair.git
  - name: opentelekomcloud.bastion
    # src: https://github.com/opentelekomcloud/ansible-role-otc-bastion.git
  - name: opentelekomcloud.server_common
    # src: https://github.com/opentelekomcloud/ansible-role-otc-server-common.git
  - name: opentelekomcloud.security_group
