telegraf_install_version: stable
telegraf_runas_user: telegraf
telegraf_runas_group: telegraf
telegraf_configuration_template: telegraf.conf.j2

telegraf_agent_interval: 10s
telegraf_round_interval: "true"
telegraf_metric_batch_size: "1000"
telegraf_metric_buffer_limit: "10000"

telegraf_collection_jitter: 0s
telegraf_flush_interval: 10s
telegraf_flush_jitter: 0s
telegraf_debug: "false"
telegraf_quiet: "false"
telegraf_hostname:
telegraf_omit_hostname: "false"
telegraf_install_url:

telegraf_influxdb_urls: []
telegraf_influxdb_database: telegraf
telegraf_influxdb_precision: s
telegraf_influxdb_retention_policy: autogen
telegraf_influxdb_write_consistency: any

telegraf_influxdb_timeout: 5s
telegraf_influxdb_username:
telegraf_influxdb_password:
telegraf_influxdb_user_agent:
telegraf_influxdb_udp_payload:

telegraf_plugins_base:
  - name: mem
  - name: cpu
    options:
      percpu: "false"
      totalcpu: "true"
      fielddrop:
        - "time_*"
  - name: procstat
    options:
      exe: "influxd"
      prefix: "influxdb"
  - name: net
    options:
      interfaces:
        - "eth*"
        - "enp0s[0-1]"
        - "lo"
        - "ens3"

telegraf_plugins: "{{ telegraf_plugins_base }} + {{ telegraf_plugins_extra | default([]) }}"
telegraf_influxdata_base_url: "https://repos.influxdata.com"
