---
- name: Create main network
  openstack.cloud.network:
    name: "{{ scenario_name }}_network"
  register: net

- name: Getting info about external network
  openstack.cloud.networks_info:
    name: "admin_external_net"
  register: ext_net

- name: Create subnet
  openstack.cloud.subnet:
    name: "{{ scenario_name }}_subnet"
    network_name: "{{ net.network.name }}"
    cidr: "{{ subnet_cidr }}"
    dns_nameservers:
          - 100.125.4.25
          - 100.125.129.199
  register: subnet

- name: Create router
  openstack.cloud.router:
    name: "{{ scenario_name }}_router"
    enable_snat: true
    network: "{{ ext_net.openstack_networks[0].id }}"
    interfaces:
      - "{{ subnet.subnet.name }}"
  register: router

