---
- name: Delete router
  openstack.cloud.router:
    name: "{{ public_router_scenario }}_router"
    state: absent

- name: Delete subnet
  openstack.cloud.subnet:
    name: "{{ public_router_scenario }}_subnet"
    state: absent

- name: Delete main network
  openstack.cloud.network:
    name: "{{ public_router_scenario }}_network"
    state: absent
