---
- name: Create loadbalancer
  opentelekomcloud.cloud.loadbalancer:
    name: "{{ scenario_name }}_elastic_loadbalancer_http"
    state: present
    vip_subnet: "{{ loadblcr_subnet_id }}"
    vip_address: "{{ loadblcr_lb_local_ip }}"
    auto_public_ip: true
  register: loadbalancer

- name: Create listener
  opentelekomcloud.cloud.lb_listener:
    state: present
    name: "{{ scenario_name }}_listener_http"
    protocol: "{{ loadblcr_protocol }}"
    protocol_port: "{{ loadblcr_protocol_port }}"
    loadbalancer: "{{ loadbalancer.loadbalancer.id }}"
  register: listener

- name: Create lb pool
  opentelekomcloud.cloud.lb_pool:
    state: present
    name: "{{ scenario_name }}_pool_http"
    protocol: "{{ loadblcr_protocol }}"
    lb_algorithm: "{{ loadblcr_pool_lb_method }}"
    listener: "{{ listener.listener.id }}"
  register: lb_pool

- name: Create members for a pool in the load balancer
  opentelekomcloud.cloud.lb_member:
    state: present
    name: "{{ scenario_name }}_member_{{ my_idx|int +1 }}"
    pool: "{{ lb_pool.server_group.id }}"
    address: "{{ item.openstack.private_v4 }}"
    protocol_port: "{{ loadblcr_protocol_port }}"
    subnet: "{{ loadblcr_subnet_id }}"
  register: members
  loop: "{{ loadblcr_instances.results }}"
  loop_control:
    index_var: my_idx
