---
- name: Create loadbalancer
  opentelekomcloud.cloud.loadbalancer:
    name: "{{ loadbalancer_prefix }}_elastic_loadbalancer_http"
    state: present
    vip_subnet: "{{ loadbalancer_subnet_id }}"
    vip_address: "{{ loadbalancer_lb_local_ip }}"
    auto_public_ip: true
  register: loadbalancer

- name: Create listener http
  opentelekomcloud.cloud.lb_listener:
    state: present
    name: "{{ loadbalancer_prefix }}_listener_http"
    protocol: "{{ loadbalancer_http_protocol }}"
    protocol_port: "{{ loadbalancer_http_protocol_port }}"
    loadbalancer: "{{ loadbalancer.loadbalancer.id }}"
  register: listener_http

- name: Create listener https
  opentelekomcloud.cloud.lb_listener:
    state: present
    name: "{{ loadbalancer_prefix }}_listener_https"
    protocol: "{{ loadbalancer_https_protocol }}"
    protocol_port: "{{ loadbalancer_https_protocol_port }}"
    loadbalancer: "{{ loadbalancer.loadbalancer.id }}"
  register: listener_https

- name: Create listener tcp
  opentelekomcloud.cloud.lb_listener:
    state: present
    name: "{{ loadbalancer_prefix }}_listener_tcp"
    protocol: "{{ loadbalancer_tcp_protocol }}"
    protocol_port: "{{ loadbalancer_tcp_protocol_port }}"
    loadbalancer: "{{ loadbalancer.loadbalancer.id }}"
  register: listener_tcp

- name: Create lb pool
  opentelekomcloud.cloud.lb_pool:
    state: present
    name: "{{ loadbalancer_prefix }}_pool_http"
    protocol: "{{ loadbalancer_protocol }}"
    lb_algorithm: "{{ loadbalancer_pool_lb_method }}"
    listener: "{{ listener.listener.id }}"
  register: lb_pool

- name: Create members for a pool in the load balancer
  opentelekomcloud.cloud.lb_member:
    state: present
    name: "{{ loadbalancer_prefix }}_member_{{ my_idx|int +1 }}"
    pool: "{{ lb_pool.server_group.id }}"
    address: "{{ item.openstack.private_v4 }}"
    protocol_port: "{{ loadbalancer_protocol_port }}"
    subnet: "{{ loadbalancer_subnet_id }}"
  register: members
  loop: "{{ loadbalancer_instances.results }}"
  loop_control:
    index_var: my_idx

- name: Enable health check
  opentelekomcloud.cloud.lb_healthmonitor:
    state: present
    name: "{{ loadbalancer_prefix }}_healthcheck"
    pool: "{{ lb_pool.server_group.id }}"
    delay: "{{ loadbalancer_monitor_delay }}"
    max_retries: "{{ loadbalancer_monitor_max_retries }}"
    monitor_timeout: "{{ loadbalancer_monitor_timeout }}"
    type: "{{ loadbalancer_protocol }}"
