---
- name: Prepare Statsdaemon directory
  file:
    state: directory
    path: "{{ statsdaemon_home }}"

- name: Get archive
  get_url:
    url: "{{ statsdaemon_url }}"
    dest: "{{ statsdaemon_destination }}"

- name: Unarchive statsdaemon
  unarchive:
    src: "{{ statsdaemon_destination }}"
    dest: "{{ statsdaemon_home }}"
    copy: no
    creates: "{{ statsdaemon_unarchieved }}"

- name: Setup statsdaemon upstart.conf
  template:
    src: upstart.conf.j2
    dest: /etc/init/statsdaemon.conf
  when: statsdaemon_service == 'upstart'
  notify: statsdaemon restart

- name: Setup statsdaemon systemd.conf
  template:
    src: systemd.conf.j2
    dest: /etc/systemd/system/statsdaemon.service
  when: statsdaemon_service == 'systemd'
  notify: statsdaemon restart

- name: Ensure that Statsdaemon is started
  service:
    name: statsdaemon
    state: started
    enabled: yes
