---
#- name: Prepare Infrastructure
#  hosts: local
#  vars:
#    - prefix: scn2-
#  tasks:
#  - name: Create Keypair
#    include_role:
#      name: opentelekomcloud.keypair
#  - name: Create VPC (Router + Net + Subnet)
#    include_role:
#      name: opentelekomcloud.vpc
#  - name: Create Server with all required resources
#    include_role:
#      name: opentelekomcloud.bastion
#    vars:
#      server_flavor: 's2.medium.1'
#      server_image: 'Standard_CentOS_7_latest'
#      domain_name: 'scn2_ecs'
#      server_keypair_name: "{{ (prefix + 'KeyPair') }}"
#      server_fqdn: "{{ test_server_fqdn }}"

# TODO: implement infrastructure creation
# add_host: ...

- name: Setup DB
  hosts: scn2_db
  become: yes
  roles:
  - geerlingguy.postgresql
  vars:
    postgresql_locales:
      - 'en_US.UTF-8'
    postgresql_version: '10.0'
    postgresql_databases:
      - name: "{{ PG_DATABASE }}"
    postgresql_users:
      - name: "{{ PG_USERNAME }}"
        password: "{{ PG_PASSWORD }}"

- name: Start Server
  hosts: scn2_ecs
  roles:
  - too_simple_server
  vars:
    pg_db_url: "{{ PG_DB_URL }}"
    pg_database: "{{ PG_DATABASE }}"
    pg_username: "{{ PG_USERNAME }}"
    pg_password: "{{ PG_PASSWORD }}"
    debug: False
