---

- name: Install xinetd
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: xinetd
    state: latest
  tags: skip_ansible_lint

- name: Gather forwards from inventory variable
  set_fact:
    forwardings_list: "{{ (item[:10] == 'scn1_basic') |ternary (forwardings_list | default([]) |
    union([{'name': item, 'ip': hostvars[item].ansible_host, 'port': hostvars[item].ansible_port}]) ,
     forwardings_list | default([])) }}"
  with_items: "{{ groups.scn1_gatewayed }}"
  tags: skip_ansible_lint

- name: Configure xinetd forwards
  template:
    src: 'templates/xinetd_forward.conf'
    dest: '/etc/xinetd.d/{{ item.name }}'
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ forwardings_list }}"
  notify:
    - reload xinetd
