---
- name: Prepare controller variables
  import_playbook: setup_scenarios_controller.yml

- name: Prepare variables
  hosts: localhost
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
    TF_VAR_network_id: "{{ network_id }}"
    TF_VAR_router_id: "{{ router_id }}"
    TF_VAR_subnet_id: "{{ subnet_id }}"
    TF_VAR_subnet_cidr: "{{ subnet_cidr }}"
    TF_VAR_controller_public_ip: "{{ controller_public_ip }}"
  vars:
    scenario_name: rds_monitoring
    terraform_base_dir: terraform
    requirements: requirements.txt
    terraform_workspace: prod
    key_name: "key_{{ scenario_name }}"
    infra_state: absent
  roles:
    - build_infrastructure