---
- name: Prepare controller variables
  import_playbook: ../setup_scenarios_controller.yml

- name: Prepare variables
  hosts: localhost
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
  vars:
    scenario_name: "rds_monitoring"
    terraform_base_dir: "terraform"
    requirements: "requirements.txt"
  roles:
    - build_infrastructure
  tasks:
    - name: Register build result
      set_fact:
        db_password: "{{ tf_output.outputs[\"db_password\"].value }}"
        db_username: "{{ tf_output.outputs[\"db_username\"].value }}"
        db_address: "{{ tf_output.outputs[\"db_address\"].value }}"
        scn2_public_ip: "{{ tf_output.outputs[\"scn2_public_ip\"].value }}"
