---
- name: Prepare controller variables
  import_playbook: ../setup_scenarios_controller.yml

- name: Prepare variables
  hosts: localhost
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
  vars:
    scenario_name: "sfs_monitoring"
    terraform_base_dir: "terraform"
    requirements: "requirements.txt"
  roles:
    - build_infrastructure
  tasks:
    - name: Register build result
      set_fact:
        bastion_public_ip: "{{ tf_output.outputs['scn3_5_bastion_fip'].value }}"
        scn3_5_initiator_ip: "{{ tf_output.outputs['scn3_5_initiator_instance_ip'].value }}"
        scn3_5_target_ip: "{{ tf_output.outputs['scn3_5_target_instance_ip'].value }}"
        scn3_5_sfs_path: "{{ tf_output.outputs['scn3_5_sfs_data'].value }}"
