---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
    test_host:
      ansible_connection: local
      clouds_yaml_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
      tmp_dir: "{{ clouds_yaml_file | dirname }}"
