---
- name: debian install
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'
- name: install py3 ansible version
  pip:
    executable: pip3
    name:
      - ansible
      - ansible-lint
    state: latest
