---
- name: Delete instances
  openstack.cloud.server:
    state: absent
    name: "{{ ecs_scenario_name }}_instance{{ item }}_{{ ecs_availability_zone }}"
  with_sequence: start=1 end="{{ ecs_count|int }}"

- name: Delete security group
  openstack.cloud.security_group:
    state: absent
    name: ecs_group
