---
- name: Delete instances
  openstack.cloud.server:
    state: absent
    name: "{{ ecs_name | default( ecs_scenario_name + '_instance' \
            + item + '_' + ecs_availability_zones[item|int % az_count|int] ) }}"
  with_sequence: start=1 end="{{ ecs_count|int }}"

- name: Delete ports
  openstack.cloud.port:
    name: "{{ ecs_name | default( ecs_scenario_name + '_' + item) }}_port"
    state: absent
  with_sequence: start=1 end="{{ ecs_count|int }}"

- name: Delete security group
  openstack.cloud.security_group:
    state: absent
    name: "{{ ecs_name | default(ecs_scenario_name) }}_ecs_group"
