---
- name: Gather information about a current image
  openstack.cloud.image_info:
    image: "{{ image }}"
  register: image

- name: Create security group
  openstack.cloud.security_group:
    state: present
    name: ecs_group
    description: Allow external connections to ssh, http, https and icmp
  register: secur_group

- name: Add rules for tcp connection to the security group
  openstack.cloud.security_group_rule:
    security_group: "{{ secur_group.secgroup.name }}"
    protocol: tcp
    port_range_min: "{{ item }}"
    port_range_max: "{{ item }}"
    remote_ip_prefix: 0.0.0.0/0
  loop:
    - 22
    - 80
    - 443

- name: Add a rule for icmp connection to the security group
  openstack.cloud.security_group_rule:
    security_group: "{{ secur_group.secgroup.name }}"
    protocol: icmp
    port_range_min: -1
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0

- name: Create a new instance
  os_server:
    state: present
    name: "{{ scenario_name }}_instance{{ item }}"
    flavor: "{{ flavor }}"
    key_name: "{{ key_pair }}"
    availability_zone: "{{ availability_zone }}"
    timeout: 200
    nics:
      - net-name: "test-polina_csm_controller_router"
      - net-id: "209dc3cb-753f-42c2-afe0-b3f8fc91da94"
    volume_size: "{{ volume_size }}"
    image: "{{ image.openstack_image.id }}"
    terminate_volume: true
  with_sequence: start=0 end="{{ count }}"