ecs_image: "{{ ecs_image }}"
nodes_count: "{{ nodes_count }}"
network_id: "{{ network_id }}"
subnet_id: "{{ subnet_id }}"
subnet_cidr: "{{ subnet_cidr }}"
ecs_flavor: "{{ ecs_flavor }}"
key_pair_name: "{{ key_pair_name }}"
availability_zone: "{{ availability_zone }}"
disc_volume: "{{ disk_volume }}"
scneario: "{{ scenario }}"