---
- name: Create main network
  openstack.cloud.network:
    name: "{{ nat_gateway_scenario }}_network"
  register: net_natgw

- name: Getting info about external network
  openstack.cloud.networks_info:
    name: "admin_external_net"
  register: ext_net

- name: Create subnet
  openstack.cloud.subnet:
    name: "{{ nat_gateway_scenario }}_subnet"
    network_name: "{{ net_natgw.network.name }}"
    cidr: "{{ nat_gateway_subnet_cidr }}"
    dns_nameservers:
          - 100.125.4.25
          - 100.125.129.199
          - 8.8.8.8
  register: subnet_natgw

- name: Create router
  openstack.cloud.router:
    name: "{{ nat_gateway_scenario }}_router"
    enable_snat: false
    network: "{{ ext_net.openstack_networks[0].id }}"
    interfaces:
        - net: "{{ net_natgw.network.name }}"
          subnet: "{{ subnet_natgw.subnet.name }}"
  register: router_natgw

- name: Create NAT gateway
  opentelekomcloud.cloud.nat_gateway:
    name: "{{ nat_gateway_scenario }}_nat_gateway"
    internal_network: "{{ net_natgw.network.name }}"
    router: "{{ router_natgw.router.name }}"
  register: nat_gw

- name: Allocate EIP for SNAT rule
  opentelekomcloud.cloud.floating_ip:
    network: admin_external_net
  register: fip

- name: Add SNAT rule
  opentelekomcloud.cloud.nat_snat_rule:
    nat_gateway: "{{ nat_gw.gateway.name }}"
    network: "{{ net_natgw.network.name }}"
    floating_ip: "{{ fip.floating_ip.floating_ip_address }}"
  register: snat
  ignore_errors: true

- name: Launch a server instance
  openstack.cloud.server:
    name: "{{ nat_gateway_instance_name }}"
    image: "{{ nat_gateway_instance_image }}"
    network: "{{ net_natgw.network.id }}"
    flavor: "{{ nat_gateway_instance_flavor }}"
    auto_ip: false
