- name: Delete a server instance
  openstack.cloud.server:
    name: "{{ nat_gateway_instance_name }}"
    image: "{{ nat_gateway_instance_image }}"
    network: "{{ net_natgw.network.id }}"
    flavor: "{{ nat_gateway_instance_flavor }}"
    auto_ip: false
    state: absent

- name: Allocate EIP for SNAT rule
  opentelekomcloud.cloud.floating_ip:
    state: absent
    server: "{{ nat_gateway_scenario }}_nat_gateway"

- name: Create NAT gateway
  opentelekomcloud.cloud.nat_gateway:
    name: "{{ nat_gateway_scenario }}_nat_gateway"
    internal_network: "{{ net_natgw.network.name }}"
    router: "{{ router_natgw.router.name }}"
    state: absent

- name: Create router
  openstack.cloud.router:
    name: "{{ nat_gateway_scenario }}_router"
    state: absent

- name: Create subnet
  openstack.cloud.subnet:
    name: "{{ nat_gateway_scenario }}_subnet"
    state: absent

- name: Create main network
  openstack.cloud.network:
    name: "{{ nat_gateway_scenario }}_network"
    state: absent
