---
- name: Build a main network with a router
  include_role:
    name: "{{ item }}"
  loop:
    - public_router
    - bastion
  vars:
    state: present
    public_router_scenario: "{{ scenario_name }}"
    bastion_image: "{{ csm_controller_image }}"
    bastion_network_id: "{{ net.network.id }}"
    bastion_private_ip: "{{ csm_controller_subnet | ansible.netcommon.ipmath(2) }}"
    bastion_flavor: "{{ csm_controller_flavor }}"
    bastion_key_pair_name: "{{ csm_controller_keypair_name }}"
    bastion_volume_size: "{{ csm_controller_volume_size }}"