---
- name: Build a main network with a router
  include_role:
    name: "{{ item }}"
  loop:
    - public_router
    - opentelekomcloud.bastion
  vars:
    state: present
    public_router_subnet_cidr: "{{ network_cidr }}"
    public_router_scenario: "public_router"
    security_group: "{{ scenario_name }}_securgr"
    server_net: "{{ net.network.name }}"
    server_keypair_name: "{{ keypair_name }}"
    server_name: "{{ scenario_name }}_bastion"
    domain_name: "{{ domain }}"
