---
- name: Build a main network with a router
  hosts: local
  vars:
    infra_state: present
  roles:
    - role: public_router

- name: Build bastion
  hosts: local
  vars:
    state: present
    security_group: my_bastion_sg
    server_net: "{{ net.network.name }}"
    server_keypair_name: test-polina_kp_csm_controller
    server_name: 'bastion'
  roles:
    - role: opentelekomcloud.bastion
