---
- name: Build a main network with a router
  include_role:
    name: "{{ item }}"
  loop:
    - public_router
    - bastion
  vars:
    state: present
    bastion_image: "{{ image }}"
    bastion_network_id: "{{ net.network.id }}"
    bastion_flavor: "{{ flavor }}"
    bastion_key_pair_name: "{{ keypair_name }}"
