---
- name: Preparations for cms controller building
  include_tasks: pre_build.yaml

- name: Build csm controller
  include_tasks: build.yaml
  when: state == "present"

- name: Destroy csm controller
  include_tasks: destroy.yaml
  when: state == "absent"
