terraform_version: 0.14.0
local_private_key: "~/.ssh/{{ key_name }}"
test_host_keyfile: "/tmp/test_host_rsa"
terraform_workspace: prod
proxy_command: >
  -o UserKnownHostsFile=/dev/null
  -o ProxyCommand='ssh -W %h:%p
  -q linux@{{ controller_public_ip }}
  -i {{ local_private_key }}
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null'
  -o PasswordAuthentication=no