terraform_version: 0.14.0
tmp_dir: "/tmp"
local_private_key: "{{ tmp_dir }}/{{ key_name }}"
terraform_workspace: temp
terraform_network_cidr: "192.168.0.0/16"
os_cloud_profile: devstack
terraform_base_dir: terraform
key_name: key_csm_controller
requirements: requirements.txt
kms_key: csm_kms_key
