tmp_dir: "/tmp"
network_cidr: "192.168.0.0/16"
key_name: key_csm_controller
local_private_key: "{{ tmp_dir }}/{{ key_name }}"
requirements: requirements.txt
kms_key: csm_kms_key
ansible_ssh_user: linux
ansible_ssh_private_key_file: "{{ local_private_key }}"
container_name: "csm"
telegraf_graphite_url: localhost:2003
telegraf_graphite_env: production_eu-de
