---
- name: Destroing
  block:
  - name: Destroy infrastructure
    environment: "{{ default_variables }}"
    terraform:
      state: absent
      workspace: "{{ terraform_workspace }}"
      force_init: true
      project_path: "{{ terraform_remote_dir }}/{{ scenario_name }}"
      backend_config: "{{ backend_config }}"
