- name: Terraform pre_build
  include_tasks: pre_build.yaml

- name: Terraform build
  include_tasks: build.yaml
  when: infra_state == "present"

- name: Terraform destroy
  include_tasks: destroy.yaml
  when: infra_state == "absent"
