tmp_dir: "/tmp"
key_name: null
terraform_base_dir: infrastructure

username: null
password: null

desired_state: present
terraform_workspace: test

os_cloud_config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
os_cloud_profile: "{{ lookup('env', 'OS_CLOUD') }}"

aws_credential:
  secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  access: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
  token: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

terraform_plugin_dir: "{{ lookup('env','HOME') }}/.terraform.d/plugin-cache"

terraform_variables: {}
