---
- name: Setup software
  hosts: local
  vars:
    requirements:
      - "requirements"
    req_dir: "/tmp/requirements/"
  roles:
    - role: anton_sidelnikov.terraform
      become: yes
      vars:
        terraform_version: "{{ terraform_version }}"
  tasks:
    - name: Copy Requirements
      copy:
        src: "{{ item }}.txt"
        dest: "{{ req_dir }}"
      with_items: "{{ requirements }}"
    - name: Install requirements
      pip:
        executable: pip3
        requirements: "{{ req_dir }}{{ item }}.txt"
      with_items: "{{ requirements }}"

- name: Build/Check controller infrastructure
  hosts: local
  roles:
    - build_infrastructure
  vars:
    scenario_name: csm_controller
    controller_eip: "{{ controller_address }}"
    infra_state: present
    terraform_variables:
      kms_key: "{{ kms_key }}"
  tasks:
    - name: Register build result
      set_fact:
        controller_public_ip: "{{ tf_output.outputs['csm_controller_fip'].value }}"
        main_network_id: "{{ tf_output.outputs['network'].value }}"
        main_subnet_id: "{{ tf_output.outputs['subnet'].value }}"
        main_router_id: "{{ tf_output.outputs['router'].value }}"

    - name: Move private key to tmp_dir
      fetch:
        src: "{{ tmp_dir }}/{{ key_name }}"
        dest: "{{ local_private_key }}"
        flat: yes

    - name: Change mode of private key to 0o600
      file:
        path: "{{ local_private_key }}"
        mode: 0600

    - name: Register csm_controller
      add_host:
        name: controller
        ansible_host: "{{ controller_public_ip }}"
        ansible_ssh_user: linux
        ansible_ssh_private_key_file: "{{ local_private_key }}"

- name: Wait for hosts
  hosts: controller
  gather_facts: no
  tasks:
    - name: Wait for host to be up
      wait_for_connection:
        timeout: 120

- name: Install and setup nginx on Controller
  hosts: controller
  become: yes
  vars_files:
    - "./vars/nginx_controller.yaml"
  roles:
    - role: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: yes
        nginx_vhosts:
          - listen: "80"
            server_name: "localhost"
            extra_parameters: "{{ extra_parameters }}"
