---
- name: Prepare current host
  hosts: local
  roles:
    - role: anton_sidelnikov.terraform
      become: yes

- name: Build/Check controller infrastructure
  hosts: local
  roles:
    - build_infrastructure
  vars:
    scenario_name: csm_controller
    infra_state: present
  tasks:
    - name: Register build result
      set_fact:
        controller_public_ip: "{{ tf_output.outputs['csm_controller_fip'].value }}"
        main_network_id: "{{ tf_output.outputs['network'].value }}"
        main_subnet_id: "{{ tf_output.outputs['subnet'].value }}"
        main_router_id: "{{ tf_output.outputs['router'].value }}"
    - name: Register csm_controller
      add_host:
        name: controller
        ansible_host: "{{ controller_public_ip }}"
        ansible_ssh_user: linux
        ansible_ssh_private_key_file: "{{ local_private_key }}"

- name: Wait for hosts
  hosts: controller
  gather_facts: no
  tasks:
    - name: Wait for host to be up
      wait_for_connection:
        timeout: 120

- name: Install and setup nginx on Controller
  hosts: controller
  become: yes
  vars_files:
    - "./vars/nginx_controller.yaml"
  roles:
    - role: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: yes
        nginx_vhosts:
          - listen: "80"
            server_name: "localhost"
            extra_parameters: "{{ extra_parameters }}"
