---
- name: Build/Check controller infrastructure
  hosts: local
  roles:
    - csm_controller
  vars:
    scenario_name: csm_controller
    state: absent
  tasks:
    - name: Delete container
      opentelekomcloud.cloud.object:
        container: "{{ container_name }}"
        delete_with_all_objects: true
        mode: delete
