- name: Checking delatore processes
  hosts: test_host
  tasks:
    - name: Get running delatore processes list from remote host
      ignore_errors: yes
      shell: "ps -few | grep delatore | awk '{print $2}'"
      register: delatore_running_processes
      tags:
        - skip_ansible_lint
    - name: Debug1
      debug:
        var: "kill {{ delatore_running_processes.stdout_lines.['csm_test_utils monitor'] }}"
    - name: Debug2
      debug:
        var: "kill {{ delatore_running_processes.stdout_lines.['csm_test_utils monitor'].value }}"
