---
- name: Build/Check the main infrastructure
  import_playbook: destroy_infra.yaml
  vars:
    vpc: "vpc_a"

- name: Build/Check the main infrastructure
  import_playbook: destroy_infra.yaml
  vars:
    vpc: "vpc_b"