---
- name: Prepare controller variables
  import_playbook: setup_scenarios_controller.yml

- name: Prepare variables
  hosts: localhost
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
    TF_VAR_addr_3: "192.168.3"
    TF_VAR_network_id: "{{ main_network_id }}"
    TF_VAR_router_id: "{{ main_router_id }}"
    TF_VAR_subnet_id: "{{ main_subnet_id }}"
  vars:
    scenario_name: hdd_monitoring
    terraform_base_dir: terraform
    requirements: requirements.txt
    terraform_workspace: prod
    key_name: key_csm_controller
    infra_state: present
  roles:
    - build_infrastructure
  tasks:
  - name: Register build result
    set_fact:
      node_ips: "{{ tf_output.outputs['scn3_ecs_local_ips'].value }}"

  - name: Register nodes
    add_host:
      name: "{{ item }}"
      groups: "gatewayed"
      ansible_ssh_user: "linux"
      ansible_ssh_private_key_file: "{{ local_private_key }}"
      ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -q linux@{{ controller_public_ip }} -i {{ local_private_key }}' -o PasswordAuthentication=no"
    loop: "{{ hostvars.localhost.node_ips }}"
