---
- name: Prepare controller variables
  import_playbook: bastion_setup.yaml

- name: Prepare variables
  hosts: local
  vars:
    scenario_name: iscsi_monitoring
    infra_state: absent
  roles:
    - build_infrastructure
