---
- name: Prepare controller variables
  import_playbook: setup_scenarios_controller.yml

- name: Prepare variables
  hosts: localhost
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
    TF_VAR_network_id: "{{ main_network_id }}"
    TF_VAR_router_id: "{{ main_router_id }}"
    TF_VAR_subnet_id: "{{ main_subnet_id }}"
  vars:
    scenario_name: iscsi_monitoring
    terraform_base_dir: terraform
    requirements: requirements.txt
    terraform_workspace: prod
    key_name: "key_{{ scenario_name }}"
    infra_state: present
  roles:
    - build_infrastructure
  tasks:
  - name: Register build result
    set_fact:
      iscsi_initiator_instance_ip: "{{ tf_output.outputs['iscsi_initiator_instance_ip'].value }}"
      iscsi_target_instance_ip: "{{ tf_output.outputs['iscsi_target_instance_ip'].value }}"
