---
- name: Prepare main network with the controller host
  import_playbook: bastion_setup.yaml

- name: Create key pair for lb monitoring and including required variables
  hosts: local
  tasks:
    - name: Include variables required for lm monitoring infra
      include_vars: ./vars/lb_monitoring.yaml
    - name: Create key pair for lb monitoring scenario
      os_keypair:
        name: "{{ lb_keypair }}"
        public_key_file: "{{ local_private_key }}.pub"

- name: Build infrastructure
  hosts: local
  roles:
    - ecs_node
    - loadbalancer
  vars:
    state: present
    ecs_network_id: "{{ main_network_id }}"
    ecs_subnet_cidr: "{{ network_cidr | ansible.netcommon.ipsubnet('24', 1) }}"
    loadbalancer_subnet_id: "{{ main_subnet_id }}"
    loadbalancer_instances: "{{ instances }}"

- name: Register nodes
  hosts: local
  tasks:
    - name: Register nodes
      add_host:
        name: "{{ item.openstack.private_v4 }}"
        groups: gatewayed
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no
          -o IdentityFile="{{ local_private_key }}"
          -o User=linux
          -o PasswordAuthentication=no
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ controller_public_ip }}
          -i {{ local_private_key }}'
      loop: "{{ instances.results }}"

- name: Wait for nodes to be up
  hosts: gatewayed
  gather_facts: no
  tasks:
    - name: Wait for nodes to be up
      wait_for_connection:
        timeout: 250

- name: Install telegraf client on nodes
  hosts: gatewayed
  become: yes
  roles:
    - role: telegraf_client
      vars:
        telegraf_graphite_env: production_eu-de
        telegraf_graphite_urls:
          - http://80.158.34.215:8125
        telegraf_graphite_template: "{{ telegraf_graphite_env }}.csm.host.tags.measurement.field"
        telegraf_plugins_base:
          - name: cpu
            options:
              percpu: "false"
              totalcpu: "true"
              fielddrop:
                - "time_*"

- name: Setup nginx for TCP, HTTP, HTTPS connections
  hosts: gatewayed
  become: yes
  vars_files:
    - "./vars/nginx_http.yaml"
    - "./vars/nginx_https.yaml"
    - "./vars/nginx_tcp.yaml"
  roles:
    - role: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: yes
        nginx_vhosts:
          - listen: "3333"
            server_name: "tcp"
            extra_parameters: "{{ extra_parameters_tcp }}"
          - listen: "80"
            server_name: "http"
            extra_parameters: "{{ extra_parameters_http }}"
          - listen: "443 ssl"
            server_name: "https"
            extra_parameters: "{{ extra_parameters_https }}"

- name: Create object with data about lb infra
  hosts: local
  gather_facts: no
  tasks:
    - name: Getting data for swift object
      set_fact:
        nodes_ips: "{{ nodes_ips | default({}) |\
         combine( {item.openstack.name: item.openstack.private_v4} ) }}"
      with_items: "{{ instances.results }}"

    - name: Create object or overwrite existing object
      swift_client:
        container: "{{ container_name }}"
        object_name: "{{ scenario }}"
        content:
          loadbalancer_public_ip: "{{ loadbalancer.loadbalancer.public_vip_address }}"
          lb_instances_ips: "{{ nodes_ips | to_json }}"
          loadbalancer_private_ip: "{{ loadbalancer.loadbalancer.vip_address }}"
          loadbalancer_keypair: "{{ lb_keypair }}"
        state: present
