---
- name: Destroy infrastructure for loadbalancer monitoring
  hosts: local
  vars:
    state: absent
  vars_files:
    - ./vars/lb_monitoring.yaml
  roles:
    - loadbalancer
  tasks:
    - name: Include variables required for lm monitoring infra
      include_vars: ./vars/lb_monitoring.yaml

- name: Delete object with data about lb infra
  hosts: local
  gather_facts: no
  tasks:
    - name: Delete object with data about lb infra
      swift_client:
        container: "{{ container_name }}"
        object_name: "{{ scenario }}"
        state: absent