---
- name: Prepare main network with the controller host
  import_playbook: bastion_setup.yaml

- name: Create key pair for lb monitoring
  hosts: local
  tasks:
    - include_vars: ./vars/lb_monitoring.yaml
    - name: Create key pair for lb monitoring scenario
      openstack.cloud.keypair:
        name: "{{ lb_keypair }}"
        public_key_file: "{{ key_path }}.pub"

- name: Build infrastructure
  hosts: local
  roles:
    -  ecs_node
    -  loadbalancer
  vars:
    state: present
    ecs_network_id: "{{ main_network_id }}"
    loadbalancer_subnet_id: "{{ main_subnet_id }}"
    loadbalancer_instances: "{{ instances }}"
    loadbalancer_members_count: "{{ instances.results|length }}"
