---
- name: Destroy infrastructure for loadbalancer monitoring
  hosts: local
  vars:
    state: absent
  tasks:
    - include_vars: ./vars/lb_monitoring.yaml
  roles:
    - loadbalancer
    - ecs_node
