---
- name: Prepare main network with the controller host
  import_playbook: bastion_setup.yaml

- name: Create key pair for lb monitoring and including required variables
  hosts: local
  tasks:
    - include_vars: ./vars/lb_monitoring.yaml
    - name: Create key pair for lb monitoring scenario
      openstack.cloud.keypair:
        name: "{{ lb_keypair }}"
        public_key_file: "{{ local_private_key }}.pub"

- name: Build infrastructure
  hosts: local
  roles:
    - ecs_node
    - loadbalancer
  vars:
    state: present
    ecs_network_id: "{{ main_network_id }}"
    ecs_subnet_cidr: "{{ network_cidr | ansible.netcommon.ipsubnet('24', 1) }}"
    loadbalancer_subnet_id: "{{ main_subnet_id }}"
    loadbalancer_instances: "{{ instances }}"

- name: Register nodes
  hosts: local
  tasks:
    - name: Register nodes
      add_host:
        name: "{{ item.openstack.private_v4 }}"
        groups: gatewayed
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no
          -o IdentityFile="{{ local_private_key }}"
          -o KbdInteractiveAuthentication=no
          -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey
          -o User=linux
          -o PasswordAuthentication=no
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ controller_public_ip }}
          -i {{ local_private_key }}'
      loop: "{{ instances.results }}"


- name: Start Server
  hosts: gatewayed
  become: yes
  roles:
    - too_simple_server
  vars:
    debug: true
    server_port: 8
