---
- name: Prepare main network with the controller host
  import_playbook: bastion_setup.yaml

- name: Create key pair for lb monitoring
  hosts: local
  tasks:
    - name: Create key pair for lb monitoring scenario
      openstack.cloud.keypair:
        name: "{{ keypair }}"
        public_key_file: "{{ key_path }}.pub"
      register: keypair

- name: Build infrastructure
  hosts: local
  roles:
    -  ecs_node
    -  loadbalancer
  vars:
    state: present
    ecs_network_id: "{{ network.network.id }}"
    loadbalancer_subnet_id: "{{ subnet.subnet.id }}"
    loadbalancer_instances: "{{ instances }}"
    loadbalancer_members_count: "{{ instances.results|length }}"
