---
- name: Prepare controller variables
  import_playbook: bastion_setup.yaml

- name: Prepare variables
  hosts: local
  vars:
    scenario_name: lb_monitoring
    infra_state: present
    terraform_variables:
      network_cidr: "{{ terraform_network_cidr }}"
      network_id: "{{ main_network_id }}"
      router_id: "{{ main_router_id }}"
      subnet_id: "{{ main_subnet_id }}"
  roles:
    - build_infrastructure
  tasks:
    - name: Register build result
      set_fact:
        lb_control_instance_ip: "{{ tf_output.outputs['lb_ctrl_ip'].value }}"
        loadbalancer_public_ip: "{{ tf_output.outputs['lb_fip'].value }}"
        lb_node_ips: "{{ tf_output.outputs['lb_ecs_local_ips'].value }}"

    - name: Register nodes
      add_host:
        name: "{{ lb_control_instance_ip }}"
        groups: control
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ controller_public_ip }}
          -i {{ local_private_key }}
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null'
          -o PasswordAuthentication=no

    - name: Register nodes
      add_host:
        name: "{{ item }}"
        groups: gatewayed
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ controller_public_ip }}
          -i {{ local_private_key }}
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null'
          -o PasswordAuthentication=no
      loop: "{{ lb_node_ips }}"

- name: Wait for hosts
  hosts: gatewayed
  gather_facts: no
  tasks:
    - name: Wait for host to be up
      wait_for_connection:
        timeout: 120

- name: Start Server
  hosts: gatewayed
  become: yes
  roles:
    - too_simple_server
  vars:
    debug: true
    server_port: 80

- name: Install telegraf client on Bastion
  hosts: control
  become: yes
  vars_files:
    - ./vars/telegraf_dbconnection_vars.yaml
    - ./vars/nginx_telegraf_local.yaml
  roles:
    - role: telegraf_client
      vars:
        telegraf_influxdb_retention_policy: ""
        telegraf_plugins_base:
          - name: http_listener_v2
            options:
              service_address: "localhost:{{ telegraf_local_port }}"
              data_format: "influx"
    - role: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: yes
        nginx_vhosts:
          - listen: "80"
            server_name: "localhost"
            extra_parameters: "{{ extra_parameters }}"

- name: Install telegraf client on nodes
  hosts: gatewayed
  become: yes
  vars_files:
    - ./vars/telegraf_dbconnection_vars.yaml
  roles:
    - telegraf_client
  vars:
    telegraf_influxdb_retention_policy: ""
    telegraf_plugins_base:
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"
      - name: net
        options:
          interfaces:
            - "eth*"
            - "enp0s[0-1]"
            - "lo"
            - "ens3"

- name: Prepare runner
  hosts: control
  become: yes
  tasks:
    - name: Install csm-test-utils
      pip:
        executable: pip3
        name: csm-test-utils
