---
- include_role:
    name: nat_gateway

- name: Register host
  add_host:
    name: "{{ nat_gateway_instance_name }}"
    groups: instances
    ansible_host: "{{ nat_dnat_rule_ip }}"
    ansible_ssh_user: linux
    ansible_ssh_private_key_file: "{{ local_private_key }}"
