- name: Prepare clouds.yaml
  hosts: test_host
  vars:
    os_cloud_config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  tasks:
    - name: Register clouds location
      set_fact:
        os_cloud_config_file: "{{ os_cloud_config_file }}"
        tmp_dir: "{{ os_cloud_config_file | dirname }}"
    - name: Create tmp dir
      file:
        path: "{{ tmp_dir }}"
        state: directory
    - name: Copy clouds.yaml
      copy:
        src: "{{ os_cloud_config_file }}"
        dest: "{{ os_cloud_config_file }}"
