---
- hosts: localhost
  become: true
  tasks:

    - name: Check that the clouds.yml exists in root folder
      stat:
        path: ../clouds.yml
      register: clouds_result

    - name: Check that the secure.yml exists in root folder
      stat:
        path: ../secure.yml
      register: secure_result

    - name: Copy the clouds.yml and secure.yml to /etc/openstack, if it exist
      copy:
        src: "{{ item.src }}"
        dest: /etc/openstack
      with_items:
        - { src: '../clouds.yml'}
        - { src: '../secure.yml'}
      when: clouds_result.stat.exists and secure_result.stat.exists