---
- include_role:
    name: public_router
  vars:
    public_router_scenario: "{{ vpc_name }}"

- name: Setting facts about created infra
  set_fact:
    main_network_id: "{{ net.network.id }}"
    main_subnet_id: "{{ subnet.subnet.id }}"
    main_router_id: "{{ router.router.id }}"

- name: Setting facts about created infra
  set_fact:
    vpcs_info: "{{ vpcs_info | default({}) | combine( {vpc_name: {'network_id': main_network_id, \
                                              'subnet_id': main_subnet_id, 'router_id': main_router_id}} ) }}"
