---
- name: Prepare controller variables
  import_playbook: bastion_setup.yaml

- name: Prepare variables
  hosts: local
  vars:
    scenario_name: rds_backup_monitoring
    infra_state: present
    terraform_variables:
      network_id: "{{ main_network_id }}"
      router_id: "{{ main_router_id }}"
      subnet_id: "{{ main_subnet_id }}"
      psql_password: "Spaciba2020!"
  roles:
    - build_infrastructure
  tasks:
    - name: Register build result
      set_fact:
        cloud_name: "{{ lookup('env', 'OS_CLOUD') }}"
        ecs_instance_ip: "{{ tf_output.outputs['ecs_ip'].value }}"
        rds_instance_id: "{{ tf_output.outputs['rds_id'].value }}"
        db_password: "{{ tf_output.outputs['db_password'].value }}"
        db_username: "{{ tf_output.outputs['db_username'].value }}"
        db_address: "{{ tf_output.outputs['db_address'].value }}"
        db_host: "{{ tf_output.outputs['db_host'].value }}"
        db_port: "{{ tf_output.outputs['db_port'].value }}"
    - name: Register ecs
      add_host:
        name: "ecs"
        groups: "gatewayed"
        ansible_host: "{{ ecs_instance_ip }}"
        ansible_ssh_user: "linux"
        ansible_ssh_private_key_file: "{{ local_private_key }}"
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ controller_public_ip }}
          -i {{ local_private_key }}
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null'
          -o PasswordAuthentication=no

- name: Wait for host
  hosts: ecs
  gather_facts: no
  tasks:
    - name: Wait for host to be up
      wait_for_connection:
        delay: 5
        timeout: 120

- name: Start Server
  hosts: ecs
  become: yes
  vars:
    server_local_port: 8081
    run_option: "sqla"
    drivername: "postgresql+psycopg2"
    scenario_name: rds_backup_monitoring
    test_scripts_path: "/tmp/test-scripts"
    source: "{{ test_scripts_path }}/{{ run_option }}/data.yaml"
  roles:
    - role: too_simple_server
      vars:
        pg_db_url: "{{ hostvars.local.db_address }}"
        pg_database: "entities"
        pg_username: "{{ hostvars.local.db_username }}"
        pg_password: "{{ hostvars.local.db_password }}"
        pg_host: "{{ hostvars.local.db_host }}"
        pg_port: "{{ hostvars.local.db_port }}"
        debug: false
