---
- name: Prepare controller variables
  import_playbook: setup_scenarios_controller.yml

- name: Prepare variables
  hosts: test_host
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
    TF_VAR_network_id: "{{ main_network_id }}"
    TF_VAR_router_id: "{{ main_router_id }}"
    TF_VAR_subnet_id: "{{ main_subnet_id }}"
    TF_VAR_psql_password: "Spaciba2020!"
    OS_CLOUD: "{{ lookup('env', 'OS_CLOUD') }}"
  vars:
    scenario_name: rds_backup_monitoring
    terraform_base_dir: terraform
    requirements: requirements.txt
    key_name: "key_csm_controller"
    infra_state: absent
  roles:
    - build_infrastructure
