---
- name: Prepare controller variables
  import_playbook: setup_scenarios_controller.yml

- name: Prepare variables
  hosts: localhost
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
    TF_VAR_network_id: "{{ main_network_id }}"
    TF_VAR_router_id: "{{ main_router_id }}"
    TF_VAR_subnet_id: "{{ main_subnet_id }}"
    TF_VAR_subnet_cidr: "{{ main_subnet_cidr }}"
    TF_VAR_controller_public_ip: "{{ controller_public_ip }}"
    TF_VAR_psql_password: "345yhhjjfgj"
  vars:
    scenario_name: rds_scenario
    terraform_base_dir: terraform
    requirements: requirements.txt
    terraform_workspace: prod
    key_name: "key_{{ scenario_name }}"
    infra_state: present
  roles:
    - build_infrastructure
  tasks:
    - name: Register build result
      set_fact:
        db_password: "{{ tf_output.outputs[\"db_password\"].value }}"
        db_username: "{{ tf_output.outputs[\"db_username\"].value }}"
        db_address: "{{ tf_output.outputs[\"db_address\"].value }}"
        scn2_public_ip: "{{ tf_output.outputs[\"scn2_public_ip\"].value }}"
