- name: Setup software
  hosts: scn4_host
  roles:
  - telegraf-client
  become: yes
  vars_files:
    - "./vars/repeat-blocks.yml"
  vars:
    telegraf_hostname: ""
    telegraf_plugins_base:
      - name: mem
      - name: diskio
        options:
          devices: ["vdb", "vdc", "vdd"]
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"
  tasks:
  - name: install nginx
    become: yes
    apt:
      name: ['nginx', 'nginx-extras']

  - name: start nginx
    become: yes
    service:
      name: nginx
      state: started
