---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Wait for host
      script: wait_for_public_ip.py "{{ lookup('env', 'BASTION_PUBLIC_IP') }}" 120
      args:
        executable: python3
    - name: Register host
      add_host:
        hostname: "{{ lookup('env', 'BASTION_PUBLIC_IP') }}"
        ansible_ssh_private_key_file: "{{ lookup('env', 'RSA_PRIVATE_KEY') }}"
        ansible_ssh_user: "linux"
        groups: scn1_ecs

- name: Setup Servers
  hosts: scn1_ecs
  tasks:
    - name: ensure private key and public one are present on Bastion
      copy:
        src: "{{ lookup('env','HOME') }}/csm-sandbox/scenarios/scenario1/{{ item }}"
        dest: "~/.ssh"
        mode: 0600
      with_items:
        - scn1_instance_rsa
        - scn1_instance_rsa.pub

    - name: Open port to basic0
      command: ssh linux@192.168.0.10 -i ~/.ssh/scn1_instance_rsa -L 2210:localhost:22 -fN -o StrictHostKeyChecking=no

    - name: Open port to basic1
      command: ssh linux@192.168.0.11 -i ~/.ssh/scn1_instance_rsa -L 2211:localhost:22 -fN -o StrictHostKeyChecking=no

    - name: Add a host alias that we reach through a tunnel
      add_host:
        hostname: 192.168.0.10
        ansible_ssh_private_key_file: "{{ lookup('env', 'RSA_PRIVATE_KEY') }}"
        ansible_ssh_user: "linux"
        ansible_host: "{{ lookup('env', 'BASTION_PUBLIC_IP') }}"
        ansible_port: 2210

    - name: Add a host alias that we reach through a tunnel
      add_host:
        hostname: 192.168.0.11
        ansible_ssh_private_key_file: "{{ lookup('env', 'RSA_PRIVATE_KEY') }}"
        ansible_ssh_user: "linux"
        ansible_host: "{{ lookup('env', 'BASTION_PUBLIC_IP') }}"
        ansible_port: 2211

- name: Start Simple Server on basic0
  hosts: 192.168.0.10
  roles:
    - too_simple_server
  vars:
    debug: True

- name: Start Simple Server on basic1
  hosts: 192.168.0.11
  roles:
    - too_simple_server
  vars:
    debug: True
