---
- name: Register existing settings for target
  hosts: local
  roles:
  - register_host
  vars:
    dnsname_or_ip: "{{ lookup('env', 'TARGET_SERVER_PUBLIC_IP') }}"
    hostname: "scn3_5_target"
    group: "scn3_5_ecs"

- name: Register existing settings for initiator
  hosts: local
  roles:
  - register_host
  vars:
    dnsname_or_ip: "{{ lookup('env', 'INITIATOR_SERVER_PUBLIC_IP') }}"
    hostname: "scn3_5_initiator"
    group: "scn3_5_ecs"

- name: Prepare attached device on target server
  hosts: scn3_5_target
  become: true
  roles:
  - iscsi_target
  vars:
    volume_group: otc_iscsi
    volume_name: otc_lun1
    incominguser_password: password
    outgoinguser_password: password
    initiator_address: "{{ lookup('env', 'INITIATOR_SERVER_PUBLIC_IP') }}"

#- name: Prepare attached device on target server
#  hosts: scn3_5_target
#  become: true
#  tasks:
#    - name: Create a ext4 filesystem on attached disks
#      filesystem:
#        fstype: ext4
#        dev: "/dev/sda"
#
#    - name: Create directories for mount
#      file:
#        path: "/mnt/scsi"
#        state: directory
#        mode: '0755'
#
#    - name: Mount up devices
#      mount:
#        path: "/mnt/scsi"
#        src: "/dev/sda"
#        fstype: ext4
#        state: mounted
