---
- name: Build infrastructure
  hosts: localhost
  become: yes
  roles:
    - build_infrastructure
  vars:
    terraform_base_dir: "../scenarios"
    scenario_name: "scenario3_5"
    key_name: "key_scenario3_5"
    requirements: "requirements.txt"
    infra_state: present

- name: Include a play with preparing
  hosts: localhost
  become: yes
  vars:
    bastion_public_ip: "{{ tf_output.outputs[\"out-scn3_5_bastion_fip\"].value }}"
    scenario_name: "scenario3_5"
    AWS_variables:
      AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
  tasks:
    - name: Checking
      debug:
        var: "{{ tf_output.outputs[\"out-scn3_5_bastion_fip\"].value }}"
    - name: Including tasks for preparing
      include_tasks: preparing.yml
    - name: 'Run scenario' # noqa 301 305
      command: "ansible-playbook -i '../inventory/prod' '{{ scenario_name }}_setup.yml'  --extra-vars '{'bastion_public_ip': {{ bastion_public_ip }}}'"
      tags:
      - skip_ansible_lint
- name: Include a play with cleaning
  vars:
    scenario_name: "scenario3_5"
  tasks:
    - name: Including tasks for cleaning
      include_tasks: cleaning.yml
