- name: Register existing settings
  hosts: local
  tasks:
    - name: Wait for host
      script: wait_for_public_ip.py "{{ lookup('env', 'SERVER_PUBLIC_IP') }}" 120
      args:
        executable: python3
    - name: Register host
      add_host:
        hostname: web_server
        ansible_ssh_host: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
        ansible_ssh_user: "linux"
        groups: scn2_ecs

- name: Start Server
  hosts: scn2_ecs
  become: yes
  roles:
  - role: too_simple_server
    vars:
      pg_db_url: "{{ lookup('env', 'PSQL_ADDRESS') }}"
      pg_database: "entities"
      pg_username: "{{ lookup('env', 'PSQL_USERNAME') }}"
      pg_password: "{{ lookup('env', 'PSQL_PASSWORD') }}"
      debug: False
      server_port: 80
  - role: telegraf-client
    vars_files:
      - "./vars/telegraf_dbconnection_vars.yml"
    vars:
      telegraf_plugins_base:
      - name: postgresql
        options:
          address: "postgres://{{ lookup('env', 'PSQL_USERNAME') }}:{{ lookup('env', 'PSQL_PASSWORD') }}@{{ lookup('env', 'PSQL_ADDRESS') }}/entities"
