---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Wait for host
      script: wait_for_public_ip.py "{{ lookup('env', 'SERVER_PUBLIC_IP') }}" 120
      args:
        executable: python3
    - name: Register host
      add_host:
        hostname: server
        ansible_ssh_host: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
        ansible_ssh_user: "linux"
        groups: scn3_ecs

- name: Format and mount attached devices on server
  hosts: scn3_ecs
  become: true
  vars:
    devices:
      sata: "/dev/vdb"
      sas: "/dev/vdc"
      ssd: "/dev/vdd"
  tasks:
    - name: Create a ext4 filesystem on attached disks
      filesystem:
        fstype: ext4
        dev: "{{ item.value }}"
      with_items: "{{ lookup('dict', devices) }}"

    - name: Create directories for mount
      file:
        path: "/mnt/{{ item.key }}"
        state: directory
        mode: '0755'
      with_items: "{{ lookup('dict', devices) }}"

    - name: Mount up devices
      mount:
        path: "/mnt/{{ item.key }}"
        src: "{{ item.value }}"
        fstype: ext4
        state: mounted
      with_items: "{{ lookup('dict', devices) }}"

#- name: Instal telegraf client on bastion
#  hosts: scn3_ecs
#  become: true
#  roles:
#  - telegraf-client
#  vars:
#    telegraf_plugins_base:
#      - name: mem
#      - name: disk
#      - name: diskio
#      - name: cpu
#        options:
#          percpu: "false"
#          totalcpu: "true"
#          fielddrop:
#            - "time_*"
#      - name: net
#        options:
#          interfaces:
#            - "eth*"
#            - "enp0s[0-1]"
#            - "lo"
#            - "ens3"