---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Wait for host
      script: wait_for_public_ip.py "{{ lookup('env', 'SERVER_PUBLIC_IP') }}" 120
      args:
        executable: python
    - name: Register host
      add_host:
        hostname: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
        ansible_ssh_private_key_file: "{{ lookup('env', 'RSA_PRIVATE_KEY') }}"
        ansible_ssh_user: "linux"
        groups: scn2_ecs

- include_playbook: scenario2_server_start.yml