---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Register host
      add_host:
        host: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
        groups: scn2_ecs

- name: Start Server
  hosts: scn2_ecs
  roles:
  - too_simple_server
  vars:
    pg_db_url: "{{ PG_DB_URL }}"
    pg_database: "{{ PG_DATABASE }}"
    pg_username: "{{ PG_USERNAME }}"
    pg_password: "{{ PG_PASSWORD }}"
    debug: False
