---
#Fix me :
#- name: Prepare clouds.yaml for test_host
#  import_playbook: prepare_config.yml

- name: Prepare variables
  hosts: test_host
  tasks:
  - name: Register scenario 6 vars
    set_fact:
      terraform_base_dir: "terraform"
      requirements: "requirements.txt"

- name: Build infrastructure
  hosts: test_host
  become: yes
  roles:
    - build_infrastructure
  environment:
    OS_CLIENT_CONFIG_FILE: "~/.config/openstack/clouds.yaml"                    #"{{ clouds_yaml_file }}"
    TF_VAR_psql_password: "test1234!"                                           #"{{ psql_password }}"
  vars:
    infra_state: present
  tasks:
  - name: Check variables
    debug:
      var: key_name
  - name: Register build result
    set_fact:
      db_password: "{{ tf_output.outputs[\"db_password\"].value }}"
      db_username: "{{ tf_output.outputs[\"db_username\"].value }}"
      db_address: "{{ tf_output.outputs[\"db_address\"].value }}"
      scn6_public_ip: "{{ tf_output.outputs[\"scn_public_ip\"].value }}"
  - name: Download private key from test_host
    fetch:
      src: "{{ tmp_dir }}/{{ key_name }}"
      dest:  "{{ local_private_key }}"
      mode: 0600
      flat: yes

- name: Register used hosts
  hosts: local
  tasks:
    - name: Register host
      add_host:
        hostname: "scn6_ecs"
        ansible_ssh_host: "{{ hostvars.test_host.scn6_public_ip }}"
        ansible_ssh_user: "linux"
        ansible_ssh_private_key_file: "{{ local_private_key }}"

- name: Wait for host
  hosts: scn6_ecs
  gather_facts: no
  tasks:
    - name: Wait for host to be up
      wait_for_connection:
        delay: 5
        timeout: 120

- name: Start Server
  hosts: scn6_ecs
  become: yes
  #vars_files:
  #  - "./vars/telegraf_dbconnection_vars.yml"
  vars:
    server_port: 8081
  roles:
    - role: too_simple_server
      vars:
        pg_db_url: "{{ hostvars.test_host.db_address }}"
        pg_database: "entities"
        pg_username: "{{ hostvars.test_host.db_username }}"
        pg_password: "{{ hostvars.test_host.db_password }}"
        debug: False
  tasks:
    - name: Register facts
      set_fact:
        server_local_port: "{{ server_port }}"
