---
- name: Register existing settings
  hosts: local
  roles:
    - register_host
  vars:
    dnsname_or_ip: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
    group: "scn6_ecs"

- name: Stop Server
  hosts: scn6_ecs
  become: yes
  roles:
    - too_simple_server
  vars:
    server_state: absent

- name: Prepare clouds.yaml for test_host
  import_playbook: prepare_config.yml

- name: Prepare variables
  hosts: test_host
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
    TF_VAR_psql_password: "test1234!"                        #change to "{{ psql_password }}" before push to master
  vars:
    terraform_base_dir: "terraform"
    requirements: "requirements.txt"
    tmp_dir: "~/tmp"                                         #delete before push to master
    key_name: "key_scn6"                                     #delete before push to master
    scenario_name: "scenario6"                               #delete before push to master
    infra_state: absent
  roles:
    - build_infrastructure