---
- name: Register existing settings
  hosts: local
  roles:
    - register_host
  vars:
    dnsname_or_ip: "{{ lookup('env', 'ECS_IP') }}"
    group: "rds_scn_ecs"

- name: Stop Server
  hosts: rds_scn_ecs
  become: yes
  roles:
    - too_simple_server
  vars:
    server_state: absent
