---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Wait for host
      script: wait_for_public_ip.py "{{ lookup('env', 'BASTION_PUBLIC_IP') }}" 120
      args:
        executable: python3

    - name: Register bastion host
      add_host:
        hostname: "{{ lookup('env', 'BASTION_PUBLIC_IP') }}"
        ansible_ssh_private_key_file: "{{ lookup('env', 'RSA_PRIVATE_KEY') }}"
        ansible_ssh_user: "linux"
        groups: scn1_ecs

    - name: Add a host alias to basic0 that we reach through a tunnel
      add_host:
        hostname: basic0
        ansible_ssh_user: "linux"
        ansible_host: "{{ lookup('env', 'BASTION_PUBLIC_IP') }}"
        ansible_port: 2210
        groups: scn1_tunneled
      register: result
    - debug:
        var: result

    - name: Add a host alias to basic1 that we reach through a tunnel
      add_host:
        hostname: basic1
        ansible_ssh_user: "linux"
        ansible_host: "{{ lookup('env', 'BASTION_PUBLIC_IP') }}"
        ansible_port: 2211
        groups: scn1_tunneled
      register: result
    - debug:
        var: result

- name: Setup portforwarding on Bastion
  hosts: scn1_ecs
  become: true
  roles:
    - scenario1_portforwarding
  vars:
    debug: True

- name: Copy ssh keys to nodes
  hosts: scn1_tunneled
  become: true
  tasks:
    - name: Ensure private key and public one are present on nodes
      copy:
        src: "{{ lookup('env','HOME') }}/csm-sandbox/scenarios/scenario1/{{ item }}"
        dest: "~/.ssh"
        mode: 0600
      with_items:
        - scn1_instance_rsa
        - scn1_instance_rsa.pub
