---
- name: Register existing settings
  hosts: local
  roles:
  - register_host
  vars:
    dnsname_or_ip: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
    group: "scn2_ecs"

- name: Stop Server
  hosts: scn2_ecs
  become: yes
  roles:
  - too_simple_server
  vars:
    server_state: absent
