---
- name: Register existing settings
  hosts: local
  roles:
    - register_host
  vars:
    hostname: "scn6_ecs"
    ansible_ssh_user: "linux"
    dnsname_or_ip:  "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
    group: "scn6_ecs"

- name: Stop Server
  hosts: scn6_ecs
  become: yes
  vars:
    server_port: 8081
    server_state: absent
  roles:
    - role: too_simple_server
      vars:
        pg_db_url: "{{ hostvars.test_host.db_address }}"
        pg_database: "entities"
        pg_username: "{{ hostvars.test_host.db_username }}"
        pg_password: "{{ hostvars.test_host.db_password }}"
        debug: True

- name: Prepare clouds.yaml for test_host
  import_playbook: prepare_config.yml

- name: Prepare variables
  hosts: test_host
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
    TF_VAR_psql_password: "test1234!"                        #change to "{{ psql_password }}" before push to master
  vars:
    terraform_base_dir: "terraform"
    requirements: "requirements.txt"
    tmp_dir: "~/tmp"                                         #delete before push to master
    key_name: "key_scn6"                                     #delete before push to master
    scenario_name: "scenario6"                               #delete before push to master
    infra_state: absent
  roles:
    - build_infrastructure