---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Wait for host
      script: wait_for_public_ip.py {{ hostvars.bastion.ansible_host }} 120
      args:
        executable: python3

- name: Start Server
  hosts: gatewayed
  become: true
  roles:
  - too_simple_server
  vars:
    debug: True
    server_port: 80

- name: Instal telegraf client on nodes
  hosts: gatewayed
  become: true
  vars_files:
    - "./vars/telegraf_dbconnection_vars.yml"
  roles:
  - telegraf-client
  vars:
    telegraf_plugins_base:
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"
      - name: net
        options:
          interfaces:
            - "eth*"
            - "enp0s[0-1]"
            - "lo"
            - "ens3"