---
- name: Register existing settings
  hosts: local
  include_role:
    name: register_host
  loop:
    - { dnsname_or_ip: "{{ lookup('env', 'TARGET_SERVER_PUBLIC_IP') }}", group: 'scn3_5_target' }
    - { dnsname_or_ip: "{{ lookup('env', 'INITIATOR_SERVER_PUBLIC_IP') }}"', group: 'scn3_5_initiator' }

- name: Prepare attached devices on server
  hosts: scn3_5_target
  become: true
  tasks:
    - name: Create a ext4 filesystem on attached disks
      filesystem:
        fstype: ext4
        dev: "/dev/sda"

    - name: Create directories for mount
      file:
        path: "/mnt/scsi"
        state: directory
        mode: '0755'

    - name: Mount up devices
      mount:
        path: "/mnt/scsi"
        src: "/dev/sda"
        fstype: ext4
        state: mounted
