- name: Setup software
  hosts: scn4_host
  roles:
  - telegraf-client
  become: yes
  vars:
    telegraf_hostname: ""
    telegraf_influxdb_urls:
      - https://influx1.eco.tsi-dev.otc-service.com:8086
    telegraf_influxdb_database: csm
    telegraf_influxdb_username: csm
    telegraf_influxdb_password: "{{ lookup('env', 'INFLUX_PSWD') }}"
    telegraf_plugins_base:
      - name: mem
      - name: diskio
        options:
          devices: ["vdb", "vdc", "vdd"]
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"
  tasks:
  - name: Start Server
    become: yes
    roles:
    - too_simple_server
    vars:
      debug: True
      server_port: 80
