---
- name: Build infrastructure
  hosts: test_host
  roles:
    - darkwizard242.terraform
    - build_infrastructure
  vars:
    scenario_name: "scenario3_5"
    terraform_base_dir: "../scenarios"
    key_name: "key_scenario3_5"
    requirements: "requirements.txt"
    infra_state: absent
