- name: Setup software
  hosts: scn4_host
  become: yes
  roles:
  - telegraf-client
  vars:
    telegraf_influxdb_urls:
      - https://influx1.eco.tsi-dev.otc-service.com:8086
    telegraf_influxdb_database: csm
    telegraf_influxdb_username: csm
    telegraf_influxdb_password: "{{ lookup('env', 'INFLUX_PSWD') }}"
    telegraf_plugins_base:
      - name: mem
      - name: diskio
        options:
          devices: ["vdb", "vdc", "vdd"]
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"
  tasks:
  - name: install nginx
    apt:
      name: ['nginx', 'nginx-extras']

  - name: start nginx
    service:
      name: nginx
      state: started
