- name: Setup software
  hosts: scn4_host
  roles:
  - telegraf-client
  become: yes
  vars_files:
    - "./vars/repeat-blocks.yml"
  vars:
    telegraf_hostname: ""
    telegraf_plugins_base:
      - name: mem
      - name: diskio
        options:
          devices: ["vdb", "vdc", "vdd"]
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"
  tasks:
  - name: Start Server
    become: yes
    roles:
    - too_simple_server
    vars:
      debug: True
      server_port: 80
