---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Wait for host
      script: wait_for_public_ip.py {{ hostvars.bastion.ansible_host }} 120
      args:
        executable: python3

#- name: Start Server
#  hosts: scn1_gatewayed
#  become: true
#  roles:
#  - too_simple_server
#  vars:
#    debug: True
#    server_port: 80

- name: Instal docker
  hosts: bastion
  become: true
  roles:
  - docker-influxdb-grafana