---
- name: Register existing settings
  hosts: local
  roles:
  - register_host
  vars:
    dnsname_or_ip: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
    group: "scn2_ecs"

- name: Start Server
  hosts: scn2_ecs
  become: yes
  roles:
  - role: too_simple_server
    vars:
      pg_db_url: "{{ lookup('env', 'PSQL_ADDRESS') }}"
      pg_database: "entities"
      pg_username: "{{ lookup('env', 'PSQL_USERNAME') }}"
      pg_password: "{{ lookup('env', 'PSQL_PASSWORD') }}"
      debug: False
      server_port: 80
  - role: telegraf-client
    vars_files:
      - "./vars/telegraf_dbconnection_vars.yml"
    vars:
      telegraf_plugins_base:
      - name: postgresql
        options:
          address: "postgres://{{ lookup('env', 'PSQL_USERNAME') }}:{{ lookup('env', 'PSQL_PASSWORD') }}@{{ lookup('env', 'PSQL_ADDRESS') }}/entities"
