---
- name: Prepare attached device on target server
  hosts: scn3_5_target_instance
  gather_facts: yes
  become: yes
  vars_files:
    - "./vars/scenario_3_5_vars.yml"
  roles:
    - iscsi_target

- name: Prepare initiator and connect device
  hosts: scn3_5_initiator_instance
  become: yes
  vars_files:
    - "./vars/scenario_3_5_vars.yml"
  tasks:
    - name: Perform a discovery on target
      open_iscsi:
        show_nodes: yes
        discover: yes
        portal: "{{ hostvars.scn3_5_target_instance.ansible_host }}"

    - name: Connect to the target
      open_iscsi:
        auto_node_startup: yes
        login: yes
        node_user: "{{ incominguser_username }}"
        node_pass: "{{ incominguser_password }}"
        portal: "{{ hostvars.scn3_5_target_instance.ansible_host }}"

- name: Prepare attached iSCSI device on initiator
  hosts: scn3_5_initiator_instance
  become: yes
  vars_files:
    - "./vars/scenario_3_5_vars.yml"
  tasks:
    - name: Add hdparm repository [Debian/Ubuntu]
      apt_repository:
        repo: deb http://deb.debian.org/debian stretch main
        state: present

    - name: Install hdparm
      apt:
        name: hdparm
        update_cache: yes

    - name: Create a ext4 filesystem on attached disks
      filesystem:
        fstype: ext4
        dev: "{{ device }}"

    - name: Create directories for mount
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: "0755"

    - name: Mount up devices
      mount:
        path: "{{ mount_point }}"
        src: "{{ device }}"
        fstype: ext4
        state: mounted

    - name: Install cron
      apt:
        pkg:
          - cron

    - name: Cron job for create big files on SCSI device every 5 minutes
      cron:
        name: "Creating big file on iSCSI device"
        minute: "*/5"
        job: /bin/dd if=/dev/urandom of="{{ mount_point }}/bigfile.txt" bs=5000000 count=100 oflag=dsync

    - name: Cron job for reading big files on all devices every 2 minutes
      cron:
        name: "Reading big files from iSCSI device"
        minute: "*/2"
        job: /sbin/hdparm -tT "{{ device }}"

- name: Install telegraf client on initiator
  hosts: scn3_5_initiator_instance
  become: yes
  vars_files:
    - "./vars/telegraf_dbconnection_vars.yml"
    - "./vars/scenario_3_5_vars.yml"
  roles:
    - telegraf-client
  vars:
    telegraf_plugins_base:
      - name: mem
      - name: diskio
        options:
          devices: ["{{ device }}"]
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"
      - name: http_listener_v2
        options:
          service_address: "localhost:8080"
          data_format: "influx"

- name: Prepare test
  hosts: scn3_5_initiator_instance
  become: yes
  tasks:
    - name: copy test script on initiator
      copy:
        src: iscsi_connection_status.sh
        dest: /tmp/

    - name: Changing perm of "iscsi_connection_status.sh", adding "+x"
      file: dest=/tmp/iscsi_connection_status.sh mode=a+x

    - name: Schedule connection test
      cron:
        name: "Check status of iSCSI connection"
        minute: "*/1"
        job: /tmp/iscsi_connection_status.sh
