---
- name: Instal telegraf client on Bastion
  hosts: bastion
  become: true
  vars_files:
  - "./vars/repeat-blocks.yml"
  - "./vars/nginx_extra_parameters.yml"
  tasks:
    - name: copy ssl keys to nginx
      copy:
        src: nginx/nginx_keys/
        dest: /etc/sslcerts/live/
  roles:
  - role: telegraf-client
    vars:
      telegraf_plugins_base:
        - name: http_listener_v2
          options:
            service_address: ":8080"
            data_format: "influx"
  - role: geerlingguy.nginx
    vars:
      nginx_vhosts:
        - listen: "443 ssl"
          server_name: "csm.outcatcher.com"
          extra_parameters: "{{ extra_parameters }}"