---
- name: Build Controller
  hosts: localhost
  tasks:
    - name: Prepare variables for build
      set_fact:
        terraform_base_dir: "terraform"
        requirements: "requirements.txt"
        terraform_workspace: "prod"
        key_name: "key_{{ scenario_name }}"
        controller_eip: "{{ controller_eip }}"

- name: Build/Check controller infrastructure
  hosts: localhost
  roles:
    - build_infrastructure
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ clouds_yaml_file }}"
  vars:
    infra_state: present
  tasks:
  - name: Register build result
    set_fact:
      controller_public_ip: "{{ tf_output.outputs['csm_controller_fip'].value }}"
      network_id: "{{ tf_output.outputs['network'].value }}"
      subnet_id: "{{ tf_output.outputs['subnet'].value }}"
      router_id: "{{ tf_output.outputs['router'].value }}"

  - name: Download private key from test_host
    fetch:
      src: "{{ tmp_dir }}/{{ key_name }}"
      dest:  "{{ local_private_key }}"
      mode: 0600
      flat: yes

  - name: Register Bastion
    add_host:
      name: "controller"
      ansible_host: "{{ controller_public_ip }}"
      ansible_ssh_user: "linux"
      ansible_ssh_private_key_file: "{{ local_private_key }}"
