- name: Setup software
  hosts: local
  vars:
    requirements:
      - "requirements"
    req_dir: "/tmp/requirements/"
  roles:
    - role: anton_sidelnikov.terraform
      become: yes
      vars:
        terraform_version: "{{ terraform_version }}"
  tasks:
    - name: Copy Requirements
      copy:
        src: "{{ item }}.txt"
        dest: "{{ req_dir }}"
      with_items: "{{ requirements }}"
    - name: Install requirements
      pip:
        executable: pip3
        requirements: "{{ req_dir }}{{ item }}.txt"
      with_items: "{{ requirements }}"
