---
- name: Register existing settings
  hosts: local
  tasks:
    - name: Store server public IP
      set_fact:
        server_ip: "{{ lookup('env', 'SERVER_PUBLIC_IP') }}"
    - name: Wait for host
      script: wait_for_public_ip.py "{{ server_ip }}" 120
      args:
        executable: python3
    - name: Register host
      add_host:
        hostname: test_host
        ansible_ssh_host: "{{ server_ip }}"
        ansible_ssh_user: "linux"

- name: Setup host
  hosts: test_host
  tasks:
  - name: Register common paths
    set_fact:
      cacheable: yes
      repo_address: 'https://github.com/opentelekomcloud-infra/customer-service-monitoring'
      csm_root_dir: '/tmp/csm'
      csm_scenarios_dir: "{{ csm_root_dir }}/scenarios"
      credentials_env:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        TF_VAR_username: "{{ lookup('env', 'OS_USERNAME') }}"
        TF_VAR_password: "{{ lookup('env', 'OS_PASSWORD') }}"
  - name: Checkout infrasctructure repository
    git:
      repo: "{{ repo_address }}"
      dest: "{{ csm_root_dir }}"
      force: yes
      depth: 1

- name: 'Build all scenarios'
  host: test_host
  tasks:
  - name: 'Build scenario'
    environment: "{{ credentials_env }}"
    shell: "{{ csm_scenarios_dir }}/build.sh scenario{{ item }}"
    with_items:
    - '1'
    - '2'
    - '3'
    - '4'
