- name: Setup software
  hosts: test_host
  tasks:
  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
  - name: Get exact python version
    shell: python3 -c "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor))"
    register: python_version
  - name: Install venv
    pip:
      requirements: 'requirements.txt'
      virtualenv: '.venv'
      virtualenv_python: "python{{ python_version.stdout }}"
  - name: Install ansible
    pip:
      requirements: 'req_ansible.txt'
      virtualenv: '.venv'
      virtualenv_python: "python{{ python_version.stdout }}"
  roles:
  - role: latest_python
    become: yes
    vars:
      min_py_version: '3.7'
  - role: darkwizard242.terraform
    become: yes
    vars:
      terraform_version: '0.12.8'