---

- name: Register used hosts
  hosts: local
  tasks:
  - name: Print some debug information
    vars:
      msg: |
        Module Variables ("vars"):
        --------------------------------
        "{{ vars | to_nice_json }} "

        Environment Variables ("environment"):
        --------------------------------
        "{{ environment | to_nice_json }} "

        GROUP NAMES Variables ("group_names"):
        --------------------------------
        "{{ group_names | to_nice_json }}"

        GROUPS Variables ("groups"):
        --------------------------------
        "{{ groups | to_nice_json }}"

        HOST Variables ("hostvars"):
        --------------------------------
        "{{ hostvars | to_nice_json }} "

    debug:
      msg: "{{ msg.split('\n') }}"
    tags: debug_info
  - name: Register vRunner
    add_host:
      name: "csmrunner"
      ansible_host: "{{ csm_runner_addr }}"
      ansible_ssh_user: "linux"
      ansible_ssh_private_key_file: "{{ vault_ssh_key }}"
      ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -q linux@{{ vcloud_bastion }}' -o PasswordAuthentication=no"


- name: Checking reporting processes
  hosts: csmrunner
  tasks:
    - name: Get reporting processes list from remote host  # noqa 301 305
      ignore_errors: yes
      shell: "ps aux | grep 'csm_test_utils monitor' | awk '{print $2}'"
      register: process_monitor
    - name: Kill running reporting processes  # noqa 301 305
      ignore_errors: yes
      shell: "kill {{ process_monitor.stdout_lines[0] }}"
    - name: Waiting for status
      wait_for:
        path: "/proc/{{ process_monitor.stdout_lines[0] }}/status"
        state: absent
      ignore_errors: yes

- name: Start reporting for scenario
  hosts: csmrunner
  tasks:
  - name: Execute csm_test_utils  # noqa 301 305
    shell: "nohup python3 -m csm_test_utils monitor --target {{ loadbalancer_public_ip }} --telegraf 'http://{{ bastion_public_ip }}' &"
