---
- name: Register used hosts
  hosts: local
  tasks:
  - name: Register vcloud_Bastion
    add_host:
      name: "vcloud_bastion"
      ansible_host: "{{ vbastion_public_ip }}"
      ansible_ssh_user: "linux"
      ansible_ssh_private_key_file: "{{ vcloud_private_key }}"
  - name: Register vcloud_csmrunner
    add_host:
      name: "vcloud_csmrunner"
      groups: "vcloud"
      ansible_host: "{{ vrunner_public_ip }}"
      ansible_ssh_user: "linux"
      ansible_ssh_private_key_file: "{{ vcloud_private_key }}"
      ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -q linux@{{ vbastion_public_ip }} -i {{ vcloud_private_key }}' -o PasswordAuthentication=no"

- name: Checking reporting processes
  hosts: vcloud_csmrunner
  tasks:
    - name: Get reporting processes list from remote host  # noqa 301 305
      ignore_errors: yes
      shell: "ps aux | grep 'csm_test_utils monitor' | awk '{print $2}'"
      register: process_monitor
    - name: Kill running reporting processes  # noqa 301 305
      ignore_errors: yes
      shell: "kill {{ process_monitor.stdout_lines[0] }}"
    - name: Waiting for status
      wait_for:
        path: "/proc/{{ process_monitor.stdout_lines[0] }}/status"
        state: absent
      ignore_errors: yes

#- name: Start reporting for scenario
#  hosts: vcloud_csmrunner
#  tasks:
#  - name: Execute csm_test_utils  # noqa 301 305
#    shell: "nohup python3 -m csm_test_utils monitor --target {{ loadbalancer_public_ip }} --telegraf 'http://{{ bastion_public_ip }}' &"
