project_name: eu-de_test_dmd
vpcs: {VPC_A: "192.168.0.0/16", VPC_B: "10.10.0.0/16"}
vpns: []
vpc_peerings: {VPC_A: "VPC_B"}

tmp_dir: /tmp
local_private_key: "{{ tmp_dir }}/{{ key_name }}"
key_name: infra-key
requirements: requirements.txt
ansible_ssh_user: linux
ansible_ssh_private_key_file: "{{ local_private_key }}"
container_name: csm
telegraf_graphite_url: localhost:2003
telegraf_graphite_env: production_eu-de
loadbalancer_private_ip: 192.168.1.5

watcher_image: Standard_Debian_10_latest
watcher_flavor: s2.medium.2
watcher_volume_size: 10
