terraform_local_dir: "{{ terraform_base_dir }}/{{ scenario_name }}"
terraform_remote_dir: "{{ tmp_dir }}/{{ terraform_base_dir }}"
key_path: "{{ tmp_dir }}/{{ key_name }}"

backend_config:
  key: "terraform_state/{{scenario_name}}"
  endpoint: "obs.eu-de.otc.t-systems.com"
  bucket: "obs-csm"
  region: "eu-de"

default_variables:
  AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
  TF_VAR_availability_zone: "eu-de-03"
  TF_VAR_ecs_flavor: "s2.medium.2"
  TF_VAR_ecs_image: "Debian_10_latest"
  TF_VAR_addr_3_octets: "192.168.0"
